clubs = [

    # ENGLAND - PREMIER LEAGUE
    {"name":"Arsenal","country":"England","league":"Premier League","reputation":92},
    {"name":"Aston Villa","country":"England","league":"Premier League","reputation":84},
    {"name":"Bournemouth","country":"England","league":"Premier League","reputation":77},
    {"name":"Brentford","country":"England","league":"Premier League","reputation":79},
    {"name":"Brighton","country":"England","league":"Premier League","reputation":82},
    {"name":"Burnley","country":"England","league":"Premier League","reputation":72},
    {"name":"Chelsea","country":"England","league":"Premier League","reputation":90},
    {"name":"Crystal Palace","country":"England","league":"Premier League","reputation":77},
    {"name":"Everton","country":"England","league":"Premier League","reputation":79},
    {"name":"Fulham","country":"England","league":"Premier League","reputation":77},
    {"name":"Leeds United","country":"England","league":"Premier League","reputation":78},
    {"name":"Liverpool","country":"England","league":"Premier League","reputation":95},
    {"name":"Manchester City","country":"England","league":"Premier League","reputation":99},
    {"name":"Manchester United","country":"England","league":"Premier League","reputation":91},
    {"name":"Newcastle United","country":"England","league":"Premier League","reputation":88},
    {"name":"Nottingham Forest","country":"England","league":"Premier League","reputation":80},
    {"name":"Sunderland","country":"England","league":"Premier League","reputation":74},
    {"name":"Tottenham Hotspur","country":"England","league":"Premier League","reputation":88},
    {"name":"West Ham United","country":"England","league":"Premier League","reputation":80},
    {"name":"Wolverhampton Wanderers","country":"England","league":"Premier League","reputation":76},

    # ENGLAND - CHAMPIONSHIP
    {"name":"Birmingham City","country":"England","league":"Championship","reputation":68},
    {"name":"Blackburn Rovers","country":"England","league":"Championship","reputation":69},
    {"name":"Bristol City","country":"England","league":"Championship","reputation":67},
    {"name":"Charlton Athletic","country":"England","league":"Championship","reputation":66},
    {"name":"Coventry City","country":"England","league":"Championship","reputation":71},
    {"name":"Derby County","country":"England","league":"Championship","reputation":68},
    {"name":"Hull City","country":"England","league":"Championship","reputation":66},
    {"name":"Ipswich Town","country":"England","league":"Championship","reputation":72},
    {"name":"Leicester City","country":"England","league":"Championship","reputation":81},
    {"name":"Middlesbrough","country":"England","league":"Championship","reputation":70},
    {"name":"Millwall","country":"England","league":"Championship","reputation":66},
    {"name":"Norwich City","country":"England","league":"Championship","reputation":72},
    {"name":"Oxford United","country":"England","league":"Championship","reputation":64},
    {"name":"Portsmouth","country":"England","league":"Championship","reputation":67},
    {"name":"Preston North End","country":"England","league":"Championship","reputation":66},
    {"name":"Queens Park Rangers","country":"England","league":"Championship","reputation":66},
    {"name":"Sheffield United","country":"England","league":"Championship","reputation":75},
    {"name":"Sheffield Wednesday","country":"England","league":"Championship","reputation":68},
    {"name":"Southampton","country":"England","league":"Championship","reputation":78},
    {"name":"Stoke City","country":"England","league":"Championship","reputation":68},
    {"name":"Swansea City","country":"England","league":"Championship","reputation":69},
    {"name":"Watford","country":"England","league":"Championship","reputation":71},
    {"name":"West Bromwich Albion","country":"England","league":"Championship","reputation":72},
]